version: "3.8"

services:
  basic_materials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_basic_materials
    environment:
      - SECTOR=Basic_Materials
    volumes:
      - shared_data:/shared_data

  communication_services:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_communication_services
    environment:
      - SECTOR=Communication_Services
    volumes:
      - shared_data:/shared_data

  consumer_cyclical:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_consumer_cyclical
    environment:
      - SECTOR=Consumer_Cyclical
    volumes:
      - shared_data:/shared_data

  consumer_defensive:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_consumer_defensive
    environment:
      - SECTOR=Consumer_Defensive
    volumes:
      - shared_data:/shared_data

  energy:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_energy
    environment:
      - SECTOR=Energy
    volumes:
      - shared_data:/shared_data

  financials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_financials
    environment:
      - SECTOR=Financials
    volumes:
      - shared_data:/shared_data

  healthcare:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_healthcare
    environment:
      - SECTOR=Healthcare
    volumes:
      - shared_data:/shared_data

  industrials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_industrials
    environment:
      - SECTOR=Industrials
    volumes:
      - shared_data:/shared_data

  real_estate:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_real_estate
    environment:
      - SECTOR=Real_Estate
    volumes:
      - shared_data:/shared_data

  technology:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_technology
    environment:
      - SECTOR=Technology
    volumes:
      - shared_data:/shared_data

  utilities:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_utilities
    environment:
      - SECTOR=Utilities
    volumes:
      - shared_data:/shared_data

  analysis:
    build: .
    command: ["sh", "-c", "python analysis.py && exit"]
    container_name: analysis_container
    volumes:
      - shared_data:/shared_data  # ✅ Matches everything
    depends_on:
      technology:
        condition: service_completed_successfully
      healthcare:
        condition: service_completed_successfully
      financials:
        condition: service_completed_successfully
      basic_materials:
        condition: service_completed_successfully
      communication_services:
        condition: service_completed_successfully
      consumer_cyclical:
        condition: service_completed_successfully
      consumer_defensive:
        condition: service_completed_successfully
      energy:
        condition: service_completed_successfully
      industrials:
        condition: service_completed_successfully
      real_estate:
        condition: service_completed_successfully
      utilities:
        condition: service_completed_successfully

volumes:
  shared_data:
    driver: local  # ✅ Everything reads from the same place
