services:
  basic_materials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_basic_materials
    environment:
      - SECTOR=Basic_Materials
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  communication_services:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_communication_services
    environment:
      - SECTOR=Communication_Services
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  consumer_cyclical:
    build: .
    command: ["sh", "-c", "python Nova.py"]
    container_name: worker_consumer_cyclical
    environment:
      - SECTOR=Consumer_Cyclical
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  consumer_defensive:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_consumer_defensive
    environment:
      - SECTOR=Consumer_Defensive
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  energy:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_energy
    environment:
      - SECTOR=Energy
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  financials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_financials
    environment:
      - SECTOR=Financials
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  healthcare:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_healthcare
    environment:
      - SECTOR=Healthcare
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  industrials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_industrials
    environment:
      - SECTOR=Industrials
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  real_estate:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_real_estate
    environment:
      - SECTOR=Real_Estate
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  technology:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_technology
    environment:
      - SECTOR=Technology
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  utilities:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    container_name: worker_utilities
    environment:
      - SECTOR=Utilities
    volumes:
      - nova_shared_data:/shared_data
    healthcheck:
      test: ["CMD", "ls", "-A", "/shared_data"]
      interval: 10s
      retries: 3
      start_period: 5s

  analysis:
    build: .
    command: ["sh", "-c", "export RUN_ANALYSIS=true && python analysis.py && exit"]
    container_name: analysis_container
    volumes:
      - nova_shared_data:/shared_data
    depends_on:
      basic_materials:
        condition: service_healthy
      communication_services:
        condition: service_healthy
      consumer_cyclical:
        condition: service_healthy
      consumer_defensive:
        condition: service_healthy
      energy:
        condition: service_healthy
      financials:
        condition: service_healthy
      healthcare:
        condition: service_healthy
      industrials:
        condition: service_healthy
      real_estate:
        condition: service_healthy
      technology:
        condition: service_healthy
      utilities:
        condition: service_healthy

volumes:
  nova_shared_data:
    name: nova_shared_data
    driver: local
