version: "3.8"

services:
  worker_technology:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    volumes:
      - nova_shared_data:/var/lib/docker/volumes/nova_shared_data/_data
    environment:
      - SECTOR=Technology

  worker_healthcare:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    volumes:
      - nova_shared_data:/var/lib/docker/volumes/nova_shared_data/_data
    environment:
      - SECTOR=Healthcare

  worker_financials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    volumes:
      - nova_shared_data:/var/lib/docker/volumes/nova_shared_data/_data
    environment:
      - SECTOR=Financials

  worker_basic_materials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit"]
    volumes:
      - nova_shared_data:/var/lib/docker/volumes/nova_shared_data/_data
    environment:
      - SECTOR=Basic_Materials

  analysis:
    build: .
    command: ["sh", "-c", "python analysis.py && exit"]
    volumes:
      - nova_shared_data:/var/lib/docker/volumes/nova_shared_data/_data
      - ./nova_analysis:/nova_analysis
    depends_on:
      - worker_technology
      - worker_healthcare
      - worker_financials
      - worker_basic_materials

volumes:
  nova_shared_data:
    driver: local
