version: "3.9"
services:
  ############################################################################
  # GROUP 1
  ############################################################################
  basic_materials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Basic_Materials
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  communication_services:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Communication_Services
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  consumer_cyclical:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Consumer_Cyclical
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  # Dummy container that waits for group 1 to succeed
  group1_done:
    image: busybox
    command: ["sh", "-c", "echo 'Group 1 is done'"]
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - basic_materials
      - communication_services
      - consumer_cyclical

  ############################################################################
  # GROUP 2
  ############################################################################
  consumer_defensive:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Consumer_Defensive
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group1_done

  energy:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Energy
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group1_done

  financials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Financials
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group1_done

  # Dummy container that waits for group 2 to succeed
  group2_done:
    image: busybox
    command: ["sh", "-c", "echo 'Group 2 is done'"]
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - consumer_defensive
      - energy
      - financials

  ############################################################################
  # GROUP 3
  ############################################################################
  healthcare:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Healthcare
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group2_done

  industrials:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Industrials
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group2_done

  real_estate:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Real_Estate
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group2_done

  # Dummy container that waits for group 3 to succeed
  group3_done:
    image: busybox
    command: ["sh", "-c", "echo 'Group 3 is done'"]
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - healthcare
      - industrials
      - real_estate

  ############################################################################
  # GROUP 4
  ############################################################################
  technology:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Technology
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group3_done

  utilities:
    build: .
    command: ["sh", "-c", "python Nova.py && exit 0"]
    environment:
      - SECTOR=Utilities
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - group3_done

  # Dummy container that waits for group 4 to succeed
  group4_done:
    image: busybox
    command: ["sh", "-c", "echo 'Group 4 is done'"]
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - technology
      - utilities

  ############################################################################
  # FINAL ANALYSIS
  ############################################################################
  analysis:
    build: .
    command: ["sh", "-c", "export RUN_ANALYSIS=true && python analysis.py && exit 0"]
    volumes:
      - nova_shared_data:/shared_data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - group4_done

volumes:
  nova_shared_data:
    name: nova_shared_data
    driver: local
