version: "3.8"

services:
  basic_materials:
    build: .
    container_name: worker_basic_materials
    environment:
      - SECTOR=Basic_Materials
    volumes:
      - shared_data:/shared_data
    restart: always

  communication_services:
    build: .
    container_name: worker_communication_services
    environment:
      - SECTOR=Communication_Services
    volumes:
      - shared_data:/shared_data
    restart: always

  consumer_cyclical:
    build: .
    container_name: worker_consumer_cyclical
    environment:
      - SECTOR=Consumer_Cyclical
    volumes:
      - shared_data:/shared_data
    restart: always

  consumer_defensive:
    build: .
    container_name: worker_consumer_defensive
    environment:
      - SECTOR=Consumer_Defensive
    volumes:
      - shared_data:/shared_data
    restart: always

  energy:
    build: .
    container_name: worker_energy
    environment:
      - SECTOR=Energy
    volumes:
      - shared_data:/shared_data
    restart: always

  financials:
    build: .
    container_name: worker_financials
    environment:
      - SECTOR=Financials
    volumes:
      - shared_data:/shared_data
    restart: always

  healthcare:
    build: .
    container_name: worker_healthcare
    environment:
      - SECTOR=Healthcare
    volumes:
      - shared_data:/shared_data
    restart: always

  industrials:
    build: .
    container_name: worker_industrials
    environment:
      - SECTOR=Industrials
    volumes:
      - shared_data:/shared_data
    restart: always

  real_estate:
    build: .
    container_name: worker_real_estate
    environment:
      - SECTOR=Real_Estate
    volumes:
      - shared_data:/shared_data
    restart: always

  technology:
    build: .
    container_name: worker_technology
    environment:
      - SECTOR=Technology
    volumes:
      - shared_data:/shared_data
    restart: always

  utilities:
    build: .
    container_name: worker_utilities
    environment:
      - SECTOR=Utilities
    volumes:
      - shared_data:/shared_data
    restart: always

volumes:
  shared_data:
    driver: local
